### ISSUE TITLE
Missing folder ~/vscode/extensions (FileSystemError)

### ISSUE THREAD

**Issue by WaKeMaTTa** [hridoy/rails-vscode#11]
I'm having this error :

```
  ERR Error: Unable to read file '/home/user/.vscode/extensions/hridoy.rails-snippets-1.0.8/snippets/helper/form-bootstrap.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/user/.vscode/extensions/hridoy.rails-snippets-1.0.8/snippets/helper/form-bootstrap.json')
```

when I create a new file (`ctrl + n`), then I type something, then I close the file without saving it (`ctrl + w`).

**Comment by quoyi** [comment]
Not founded `snippets/helper/form-bootstrap.json` (file name error: `snippets/helper/from-bootstrap.json`) & `snippets/denug/log.json` (directory name error: `snippets/debug/log.json`) 
You can solve it by creating files and directories OR update `snippets[].path` in file `package.json`

[This is my forked repo & uploaded snippets sources](https://github.com/quoyi/rails-vscode)
